### PR TITLE
Update 1deg_jra55_ryf to restart reproducible ACCESS-OM2

### PR DESCRIPTION
**Pull request by aidanheerdegen**
Update ACCESS-OM2 to restart reproducible release

https://github.com/ACCESS-NRI/ACCESS-OM2/releases/tag/2024.03.0

Also updates to metadata, config and license as a result of QA tests.

### CODE REVIEW

**Comment by aidanheerdegen** [comment]
@CodeGat this is the PR you wanted to check to see if it works.

**Comment by CodeGat** [comment]
Seems to be working okay!

**Comment by aidanheerdegen** [comment]
I am a bit concerned because there isn't a `version` in the `metadata.yaml`. Did this pre-date that? 

Anyway ... give it a burl and see what happens.

**Comment by aidanheerdegen** [comment]
!bump major

**Comment by CodeGat** [comment]
Whoops - looks like I didn't exit after noting there was no `.version` - in the code I set it to 1.0 automatically. But in this case we didn't use the .version...? Should be a simple fix though

**Comment by aidanheerdegen** [comment]
!bump major

**Comment by CodeGat** [comment]
A few things with this one that'll be relatively quickly fixed tomorrow morning: 
* [This workflow](https://github.com/ACCESS-NRI/access-om2-configs/actions/runs/8599919061/job/23563822601#step:7:12) failed after committing correctly because the token used to comment it's success didn't have the correct permissions (@CodeGat PR this)
* [There was a direct push](https://github.com/ACCESS-NRI/access-om2-configs/actions/runs/8599788429/job/23563420932#step:4:11) to `release-*` that updated the `metadata.yaml` `.version` to `1.0` to account for the lack of it in this special case - this failed as expected because we already have that tag (this is good)
* The initial fault was because (as you noted) we didn't have a `.version` because the `generate-initial-checksums` workflow was made before we made that choice. @CodeGat There will be a PR that will rectify this
* And there seems to be a conflict between the branches at the moment which is why no more checks are firing

**Comment by aidanheerdegen** [comment]
!bump major

**Comment by aidanheerdegen** [comment]
🤦 

@CodeGat I think I did bad.

**Comment by CodeGat** [comment]
!bump major

**Comment by aidanheerdegen** [comment]
!bump major

**Comment by CodeGat** [comment]
We seemed to have hurt ourselves in our confusion. This PR will be reset and we will do it again. 
image

**Pull request closed without merging**
