### PR TITLE
New CICE grid for 0.1 deg ryf with bgc

### PR DESCRIPTION
**Pull request by anton-seaice**
Contributes to #92

### CODE REVIEW

**Review by aidanheerdegen — DISMISSED** [review]
LGTM

**Comment by aidanheerdegen** [comment]
This PR contains a lot of changes that are already in the branch but the commits are different so the rebase merge fails. 

Can you please rebase your branch on to the `dev-` branch and force push.

**Review by aidanheerdegen — APPROVED** [review]
LGTM. Thanks!

**Comment by anton-seaice** [comment]
I'm not sure we quite fixed the problem? i.e. the checksum file is missing? 

e.g. https://github.com/ACCESS-NRI/access-om2-configs/compare/dev-01deg_jra55_ryf_bgc...release-01deg_jra55_ryf_bgc shows differences

**Pull request merged**
