### PR TITLE
Update `025deg_jra55_ryf_bgc` for WOMBAT sea-ice coupling bug-fix

### PR DESCRIPTION
**Pull request by dougiesquire**
See https://github.com/ACCESS-NRI/access-om2-configs/pull/127 for details

### CODE REVIEW

**Comment by CodeGat** [comment]
@dougiesquire although it's weird that it's considering adding a commit that already exists on the remote (different hashes, though...) it would essentially be a no-op

**Comment by CodeGat** [comment]
Disregard this check. It was as a result of rebasing the `dev-*` onto `release-*`

**Comment by dougiesquire** [comment]
I think the failures here are as expected. We know that the `bgc` configs are currently [not restart reproducible](https://github.com/ACCESS-NRI/access-om2-configs/issues/112). The historical checksums differ only for the WOMBAT tracers, which makes sense because WOMBAT has changed.

```diff
$ wget https://raw.githubusercontent.com/ACCESS-NRI/access-om2-configs/f28504ed7782211b7309ee416ffd9b574f6d93d2/testing/checksum/historical-3hr-checksum.json -O historical-3hr-checksum.json.orig
$ diff -U2 historical-3hr-checksum.json.orig /scratch/tm70/repro-ci/experiments/access-om2-configs/dev-025deg_jra55_ryf_bgc/checksum/historical-3hr-checksum.json
--- historical-3hr-checksum.json.orig	2024-07-10 10:19:06.861573000 +1000
+++ /scratch/tm70/repro-ci/experiments/access-om2-configs/dev-025deg_jra55_ryf_bgc/checksum/historical-3hr-checksum.json2024-07-10 09:42:54.000000000 +1000
@@ -148,32 +148,32 @@
     ],
     "adic": [
-      "-2455395460635865998"
+      "-2455395406223065760"
     ],
     "caco3": [
-      "-1946311099822526178"
+      "-1946001330455210348"
     ],
     "alk": [
-      "666550672134593837"
+      "666550666703468188"
     ],
     "dic": [
-      "-8109352984002592935"
+      "-8109352923411889020"
     ],
     "no3": [
-      "7992606673146220590"
+      "-3927355164901111661"
     ],
     "phy": [
-      "-8977775330410481366"
+      "-5332833466290796183"
     ],
     "o2": [
-      "-2977305693613054852"
+      "-2977306008655971539"
     ],
     "fe": [
-      "-8926867780862610659"
+      "-8926870080351100871"
     ],
     "zoo": [
-      "3652579702518992198"
+      "3652619569480272960"
     ],
     "det": [
-      "-1773221676325612934"
+      "-1771932541263243583"
     ],
     "age_global": [
```

**Comment by dougiesquire** [comment]
!bump major

**Comment by dougiesquire** [comment]
`!bump major`

**Comment by CodeGat** [comment]
!bump major

**Comment by CodeGat** [comment]
!bump major

**Review by CodeGat — APPROVED** [review]

**Pull request merged**
